assessment12/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include("basic_app.urls", namespace="basic_app")),
]

assessment12/advcbv/basic_app/urls.py
from django.urls import path
from . import views

app_name = "basic_app"


urlpatterns = [
	path("", views.SchoolListView.as_view(), name="list"),
	path("<int:pk>/", views.SchoolDetailView.as_view(), name="detail"),
	path("create/", views.SchoolCreateView.as_view(), name="create"),
	path("update/<int:pk>/", views.SchoolUpdateView.as_view(), name="update"),
	path("delete/<int:pk>/", views.SchoolDeleteView.as_view(), name="delete"),
]

assessment12/advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse
from django.db.models.deletion import CASCADE

# Create your models here.


class School(models.Model):
	name = models.CharField(max_length=256)
	principal = models.CharField(max_length=256)
	location = models.CharField(max_length=256)

	def get_absolute_url(self):
		return reverse("basic_app:detail", kwargs={"pk": self.pk})


	def __str__(self):
		return self.name




class Student(models.Model):
	name = models.CharField(max_length=256)
	age = models.PositiveIntegerField()
	school = models.ForeignKey(School, related_name="students", on_delete=models.CASCADE)

	def __str__(self):
		return self.name

assessment12/advcbv/basic_app/views.py
from typing import List
from django.shortcuts import render
from django.urls.base import reverse_lazy
from . import models
from django.views.generic import (View, TemplateView, ListView, 
								DetailView, CreateView, DeleteView, 
								UpdateView)

# Create your views here.


class IndexView(TemplateView):
	template_name = "basic_app/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["injectme"] = "EVO MENE OVDE"
		return context
	


class SchoolListView(ListView):
	context_object_name = "schools"	# default is school_list
	model = models.School



class SchoolDetailView(DetailView):
	context_object_name = "school_detail"	# default is school
	model = models.School
	template_name = "basic_app/school_detail.html"


class SchoolCreateView(CreateView):
	fields = ("name", "principal", "location")
	model = models.School



class SchoolUpdateView(UpdateView):
	fields = ("name", "principal")
	model = models.School



class SchoolDeleteView(DeleteView):
	model = models.School
	success_url = reverse_lazy("basic_app:list")

assessment12/advcbv/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>
		{% block title%}
			Base
		{% endblock %}
	</title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
		<div class="navbar-nav">
			<li><a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a></li>
			<li><a class="nav-item nav-link" href="{% url 'admin:index'%}">Admin</a></li>
			<li><a class="nav-item nav-link" href="#">Sum Sum</a></li>
		</div>
	</nav>

	<div class="container">
		{% block body_block %}
		{% endblock %}
	</div>
</body>

  {# Plugins#}

  <!-- Latest compiled and minified jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</html>

assessment12/advcbv/basic_app/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}

{% block title %}
	Home Page
{% endblock %}

{% block body_block %}
	<div class="jumbotron">
		<h1>Home Page!</h1>
	</div>
{% endblock %}

assessment12/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/base.html' %}

{% block title %}
	Delete
{% endblock title %}


{% block body_block %}
	<h1>Delete {{ school.name }}?</h1>

	<form method="post">
		{% csrf_token %}
		<a class="btn btn-primary" href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
		<input type="submit" class="btn btn-danger" value="Delete">
	</form>
{% endblock body_block %}

assessment12/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/base.html' %}

{% block title %}
	School Details
{% endblock %}


{% block body_block %}
	<div class="jumbotron">
		<h1>Welcome to the School Detail Page</h1>

		<h2><b>School details:</b></h2>
		<p><b>Name:</b> {{ school_detail.name }}</p>
		<p><b>Principal:</b> {{ school_detail.principal}}</p>
		<p><b>Location:</b> {{ school_detail.location }}</p>


		<h2><b>Students:</b></h2>
		{% for student in school_detail.students.all %}
			<p>{{ student.name }} who is {{ student.age }} y/o.</p>
		{% endfor %}
	</div>

	<div class="container">
		<a class="btn btn-warning m-4" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
		<a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a>
	</div>
{% endblock %}

assessment12/advcbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/base.html' %}

{% block title %}
	Create
{% endblock %}


{% block body_block %}
	<div class="jumbotron">
		<h1>
			{% if not form.instance.pk %}
				Create School
			{% else %}
				Update School
			{% endif %}
		</h1>
	</div>

	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input class="btn btn-primary" type="submit" value="Submit">
	</form>
{% endblock %}

assessment12/advcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/base.html' %}


{% block title %}
	School List
{% endblock %}


{% block body_block %}
	<div class="jumbotron">
		<h1>Welcome to a list of all the schools!</h1>

		<ol>
			{% for school in schools %}
				<h2><li><a href="{{ school.id }}/">{{ school.name }}</a></li></h2>
			{% endfor %}
		</ol>
	</div>

{% endblock %}